//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : ������
//  @ File Name : IdUtils.java
//  @ Date : 2013-11-08
//  @ Author : 
//
//

package cn.com.softvan.common;


public class IdUtils {
//	private static final transient Logger log = Logger.getLogger(IdUtils.class);

	/**
	 * <p>
	 * 生成UUID主键
	 * </p>
	 * 
	 * @param len
	 *            位数
	 * @return 主键
	 */
	public static String createUUID(int len) {

		String uuid = java.util.UUID.randomUUID().toString()
				.replaceAll("-", "");
		return uuid.substring(0, len);
	}

	public static void main(String args[]) {
		
		for(int i=0;i<99;i++){
			System.out.println(IdUtils.createUUID(32));
		}
		
	
		
		// log.info();
	}
}
