package cn.com.softvan.cxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WebXmlImplService service = new WebXmlImplService();
 * WebXml portType = service.getWebXmlImplPort();
 * portType.saveInfo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WebXmlImplService", targetNamespace = "http://cxf.softvan.com.cn/", wsdlLocation = "http://localhost/services/webxml?wsdl")
public class WebXmlImplService extends Service {

	private final static URL WEBXMLIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.com.softvan.cxf.client.WebXmlImplService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.com.softvan.cxf.client.WebXmlImplService.class
					.getResource(".");
			url = new URL(baseUrl, "http://localhost/services/webxml?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost/services/webxml?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WEBXMLIMPLSERVICE_WSDL_LOCATION = url;
	}

	public WebXmlImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}
	public WebXmlImplService(URL url) {
		super(url, new QName(
				"http://cxf.softvan.com.cn/", "WebXmlImplService"));
	}
	public WebXmlImplService() {
		super(WEBXMLIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://cxf.softvan.com.cn/", "WebXmlImplService"));
	}

	/**
	 * 
	 * @return returns WebXml
	 */
	@WebEndpoint(name = "WebXmlImplPort")
	public WebXml getWebXmlImplPort() {
		return super.getPort(new QName("http://cxf.softvan.com.cn/",
				"WebXmlImplPort"), WebXml.class);
	}

}
